/*
Sonatype Nexus Repository Manager

Testing ManageSonatypeRepositoryFirewallConfigurationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package v3

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	sonatyperepo "github.com/sonatype-nexus-community/nexus-repo-api-client-go/v3"
)

func Test_v3_ManageSonatypeRepositoryFirewallConfigurationAPIService(t *testing.T) {

	configuration := sonatyperepo.NewConfiguration()
	apiClient := sonatyperepo.NewAPIClient(configuration)

	t.Run("Test ManageSonatypeRepositoryFirewallConfigurationAPIService CreateIqCapabilitiesTest", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManageSonatypeRepositoryFirewallConfigurationAPI.CreateIqCapabilitiesTest(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManageSonatypeRepositoryFirewallConfigurationAPIService CreateIqDisable", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.ManageSonatypeRepositoryFirewallConfigurationAPI.CreateIqDisable(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManageSonatypeRepositoryFirewallConfigurationAPIService CreateIqEnable", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.ManageSonatypeRepositoryFirewallConfigurationAPI.CreateIqEnable(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManageSonatypeRepositoryFirewallConfigurationAPIService CreateIqTestNewConnection", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManageSonatypeRepositoryFirewallConfigurationAPI.CreateIqTestNewConnection(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManageSonatypeRepositoryFirewallConfigurationAPIService GetIqAudit", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var repositoryName string

		httpRes, err := apiClient.ManageSonatypeRepositoryFirewallConfigurationAPI.GetIqAudit(context.Background(), repositoryName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManageSonatypeRepositoryFirewallConfigurationAPIService ListIq", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManageSonatypeRepositoryFirewallConfigurationAPI.ListIq(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManageSonatypeRepositoryFirewallConfigurationAPIService ListIqAudit", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManageSonatypeRepositoryFirewallConfigurationAPI.ListIqAudit(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManageSonatypeRepositoryFirewallConfigurationAPIService ListIqCapabilities", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManageSonatypeRepositoryFirewallConfigurationAPI.ListIqCapabilities(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManageSonatypeRepositoryFirewallConfigurationAPIService UpdateIq", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManageSonatypeRepositoryFirewallConfigurationAPI.UpdateIq(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManageSonatypeRepositoryFirewallConfigurationAPIService UpdateIqAudit", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.ManageSonatypeRepositoryFirewallConfigurationAPI.UpdateIqAudit(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ManageSonatypeRepositoryFirewallConfigurationAPIService VerifyIqConnection", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ManageSonatypeRepositoryFirewallConfigurationAPI.VerifyIqConnection(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
