/*
Sonatype Nexus Repository Manager

Testing SecurityManagementJWTAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package v395

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	sonatyperepo "github.com/sonatype-nexus-community/nexus-repo-api-client-go/v395"
)

func Test_v395_SecurityManagementJWTAPIService(t *testing.T) {

	configuration := sonatyperepo.NewConfiguration()
	apiClient := sonatyperepo.NewAPIClient(configuration)

	t.Run("Test SecurityManagementJWTAPIService UpdateSecurityJwt", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.SecurityManagementJWTAPI.UpdateSecurityJwt(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
