/*
Sonatype Nexus Repository Manager

Testing CapabilitiesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package v3

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	sonatyperepo "github.com/sonatype-nexus-community/nexus-repo-api-client-go/v3"
)

func Test_v3_CapabilitiesAPIService(t *testing.T) {

	configuration := sonatyperepo.NewConfiguration()
	apiClient := sonatyperepo.NewAPIClient(configuration)

	t.Run("Test CapabilitiesAPIService CreateCapabilities", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CapabilitiesAPI.CreateCapabilities(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CapabilitiesAPIService DeleteCapabilities", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var capabilityId string

		httpRes, err := apiClient.CapabilitiesAPI.DeleteCapabilities(context.Background(), capabilityId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CapabilitiesAPIService ListCapabilities", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CapabilitiesAPI.ListCapabilities(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CapabilitiesAPIService ListCapabilitiesTypes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CapabilitiesAPI.ListCapabilitiesTypes(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CapabilitiesAPIService UpdateCapabilities", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var capabilityId string

		httpRes, err := apiClient.CapabilitiesAPI.UpdateCapabilities(context.Background(), capabilityId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
