/*
Sonatype Nexus Repository Manager

This documents the available APIs into [Sonatype Nexus Repository Manager](https://www.sonatype.com/products/sonatype-nexus-repository) as of version 3.94.0-12.

API version: 3.94.0-12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// SecurityManagementPrivilegesAPIService SecurityManagementPrivilegesAPI service
type SecurityManagementPrivilegesAPIService service

type ApiCreateApplicationPrivilegeRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
	apiPrivilegeApplicationRequest *ApiPrivilegeApplicationRequest
}

// The privilege to create.
func (r ApiCreateApplicationPrivilegeRequest) ApiPrivilegeApplicationRequest(apiPrivilegeApplicationRequest ApiPrivilegeApplicationRequest) ApiCreateApplicationPrivilegeRequest {
	r.apiPrivilegeApplicationRequest = &apiPrivilegeApplicationRequest
	return r
}

func (r ApiCreateApplicationPrivilegeRequest) Execute() (*http.Response, error) {
	return r.ApiService.CreateApplicationPrivilegeExecute(r)
}

/*
CreateApplicationPrivilege Create an application type privilege.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateApplicationPrivilegeRequest
*/
func (a *SecurityManagementPrivilegesAPIService) CreateApplicationPrivilege(ctx context.Context) ApiCreateApplicationPrivilegeRequest {
	return ApiCreateApplicationPrivilegeRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *SecurityManagementPrivilegesAPIService) CreateApplicationPrivilegeExecute(r ApiCreateApplicationPrivilegeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.CreateApplicationPrivilege")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges/application"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiPrivilegeApplicationRequest == nil {
		return nil, reportError("apiPrivilegeApplicationRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.apiPrivilegeApplicationRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiCreateRepositoryAdminPrivilegeRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
	apiPrivilegeRepositoryAdminRequest *ApiPrivilegeRepositoryAdminRequest
}

// The privilege to create.
func (r ApiCreateRepositoryAdminPrivilegeRequest) ApiPrivilegeRepositoryAdminRequest(apiPrivilegeRepositoryAdminRequest ApiPrivilegeRepositoryAdminRequest) ApiCreateRepositoryAdminPrivilegeRequest {
	r.apiPrivilegeRepositoryAdminRequest = &apiPrivilegeRepositoryAdminRequest
	return r
}

func (r ApiCreateRepositoryAdminPrivilegeRequest) Execute() (*http.Response, error) {
	return r.ApiService.CreateRepositoryAdminPrivilegeExecute(r)
}

/*
CreateRepositoryAdminPrivilege Create a repository admin type privilege.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateRepositoryAdminPrivilegeRequest
*/
func (a *SecurityManagementPrivilegesAPIService) CreateRepositoryAdminPrivilege(ctx context.Context) ApiCreateRepositoryAdminPrivilegeRequest {
	return ApiCreateRepositoryAdminPrivilegeRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *SecurityManagementPrivilegesAPIService) CreateRepositoryAdminPrivilegeExecute(r ApiCreateRepositoryAdminPrivilegeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.CreateRepositoryAdminPrivilege")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges/repository-admin"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiPrivilegeRepositoryAdminRequest == nil {
		return nil, reportError("apiPrivilegeRepositoryAdminRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.apiPrivilegeRepositoryAdminRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiCreateRepositoryContentSelectorPrivilegeRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
	apiPrivilegeRepositoryContentSelectorRequest *ApiPrivilegeRepositoryContentSelectorRequest
}

// The privilege to create.
func (r ApiCreateRepositoryContentSelectorPrivilegeRequest) ApiPrivilegeRepositoryContentSelectorRequest(apiPrivilegeRepositoryContentSelectorRequest ApiPrivilegeRepositoryContentSelectorRequest) ApiCreateRepositoryContentSelectorPrivilegeRequest {
	r.apiPrivilegeRepositoryContentSelectorRequest = &apiPrivilegeRepositoryContentSelectorRequest
	return r
}

func (r ApiCreateRepositoryContentSelectorPrivilegeRequest) Execute() (*http.Response, error) {
	return r.ApiService.CreateRepositoryContentSelectorPrivilegeExecute(r)
}

/*
CreateRepositoryContentSelectorPrivilege Create a repository content selector type privilege.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateRepositoryContentSelectorPrivilegeRequest
*/
func (a *SecurityManagementPrivilegesAPIService) CreateRepositoryContentSelectorPrivilege(ctx context.Context) ApiCreateRepositoryContentSelectorPrivilegeRequest {
	return ApiCreateRepositoryContentSelectorPrivilegeRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *SecurityManagementPrivilegesAPIService) CreateRepositoryContentSelectorPrivilegeExecute(r ApiCreateRepositoryContentSelectorPrivilegeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.CreateRepositoryContentSelectorPrivilege")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges/repository-content-selector"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiPrivilegeRepositoryContentSelectorRequest == nil {
		return nil, reportError("apiPrivilegeRepositoryContentSelectorRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.apiPrivilegeRepositoryContentSelectorRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiCreateRepositoryViewPrivilegeRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
	apiPrivilegeRepositoryViewRequest *ApiPrivilegeRepositoryViewRequest
}

// The privilege to create.
func (r ApiCreateRepositoryViewPrivilegeRequest) ApiPrivilegeRepositoryViewRequest(apiPrivilegeRepositoryViewRequest ApiPrivilegeRepositoryViewRequest) ApiCreateRepositoryViewPrivilegeRequest {
	r.apiPrivilegeRepositoryViewRequest = &apiPrivilegeRepositoryViewRequest
	return r
}

func (r ApiCreateRepositoryViewPrivilegeRequest) Execute() (*http.Response, error) {
	return r.ApiService.CreateRepositoryViewPrivilegeExecute(r)
}

/*
CreateRepositoryViewPrivilege Create a repository view type privilege.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateRepositoryViewPrivilegeRequest
*/
func (a *SecurityManagementPrivilegesAPIService) CreateRepositoryViewPrivilege(ctx context.Context) ApiCreateRepositoryViewPrivilegeRequest {
	return ApiCreateRepositoryViewPrivilegeRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *SecurityManagementPrivilegesAPIService) CreateRepositoryViewPrivilegeExecute(r ApiCreateRepositoryViewPrivilegeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.CreateRepositoryViewPrivilege")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges/repository-view"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiPrivilegeRepositoryViewRequest == nil {
		return nil, reportError("apiPrivilegeRepositoryViewRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.apiPrivilegeRepositoryViewRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiCreateScriptPrivilegeRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
	apiPrivilegeScriptRequest *ApiPrivilegeScriptRequest
}

// The privilege to create.
func (r ApiCreateScriptPrivilegeRequest) ApiPrivilegeScriptRequest(apiPrivilegeScriptRequest ApiPrivilegeScriptRequest) ApiCreateScriptPrivilegeRequest {
	r.apiPrivilegeScriptRequest = &apiPrivilegeScriptRequest
	return r
}

func (r ApiCreateScriptPrivilegeRequest) Execute() (*http.Response, error) {
	return r.ApiService.CreateScriptPrivilegeExecute(r)
}

/*
CreateScriptPrivilege Create a script type privilege.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateScriptPrivilegeRequest
*/
func (a *SecurityManagementPrivilegesAPIService) CreateScriptPrivilege(ctx context.Context) ApiCreateScriptPrivilegeRequest {
	return ApiCreateScriptPrivilegeRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *SecurityManagementPrivilegesAPIService) CreateScriptPrivilegeExecute(r ApiCreateScriptPrivilegeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.CreateScriptPrivilege")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges/script"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiPrivilegeScriptRequest == nil {
		return nil, reportError("apiPrivilegeScriptRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.apiPrivilegeScriptRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiCreateWildcardPrivilegeRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
	apiPrivilegeWildcardRequest *ApiPrivilegeWildcardRequest
}

// The privilege to create.
func (r ApiCreateWildcardPrivilegeRequest) ApiPrivilegeWildcardRequest(apiPrivilegeWildcardRequest ApiPrivilegeWildcardRequest) ApiCreateWildcardPrivilegeRequest {
	r.apiPrivilegeWildcardRequest = &apiPrivilegeWildcardRequest
	return r
}

func (r ApiCreateWildcardPrivilegeRequest) Execute() (*http.Response, error) {
	return r.ApiService.CreateWildcardPrivilegeExecute(r)
}

/*
CreateWildcardPrivilege Create a wildcard type privilege.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateWildcardPrivilegeRequest
*/
func (a *SecurityManagementPrivilegesAPIService) CreateWildcardPrivilege(ctx context.Context) ApiCreateWildcardPrivilegeRequest {
	return ApiCreateWildcardPrivilegeRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *SecurityManagementPrivilegesAPIService) CreateWildcardPrivilegeExecute(r ApiCreateWildcardPrivilegeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.CreateWildcardPrivilege")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges/wildcard"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiPrivilegeWildcardRequest == nil {
		return nil, reportError("apiPrivilegeWildcardRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.apiPrivilegeWildcardRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiDeleteSecurityPrivilegesRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
	privilegeName string
}

func (r ApiDeleteSecurityPrivilegesRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteSecurityPrivilegesExecute(r)
}

/*
DeleteSecurityPrivileges Delete a privilege by name.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param privilegeName The name of the privilege to delete.
 @return ApiDeleteSecurityPrivilegesRequest
*/
func (a *SecurityManagementPrivilegesAPIService) DeleteSecurityPrivileges(ctx context.Context, privilegeName string) ApiDeleteSecurityPrivilegesRequest {
	return ApiDeleteSecurityPrivilegesRequest{
		ApiService: a,
		ctx: ctx,
		privilegeName: privilegeName,
	}
}

// Execute executes the request
func (a *SecurityManagementPrivilegesAPIService) DeleteSecurityPrivilegesExecute(r ApiDeleteSecurityPrivilegesRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.DeleteSecurityPrivileges")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges/{privilegeName}"
	localVarPath = strings.Replace(localVarPath, "{"+"privilegeName"+"}", url.PathEscape(parameterValueToString(r.privilegeName, "privilegeName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetAllPrivilegesRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
}

func (r ApiGetAllPrivilegesRequest) Execute() ([]ApiPrivilegeRequest, *http.Response, error) {
	return r.ApiService.GetAllPrivilegesExecute(r)
}

/*
GetAllPrivileges Retrieve a list of privileges.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetAllPrivilegesRequest
*/
func (a *SecurityManagementPrivilegesAPIService) GetAllPrivileges(ctx context.Context) ApiGetAllPrivilegesRequest {
	return ApiGetAllPrivilegesRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []ApiPrivilegeRequest
func (a *SecurityManagementPrivilegesAPIService) GetAllPrivilegesExecute(r ApiGetAllPrivilegesRequest) ([]ApiPrivilegeRequest, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []ApiPrivilegeRequest
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.GetAllPrivileges")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetSecurityPrivilegesRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
	privilegeName string
}

func (r ApiGetSecurityPrivilegesRequest) Execute() (*ApiPrivilegeRequest, *http.Response, error) {
	return r.ApiService.GetSecurityPrivilegesExecute(r)
}

/*
GetSecurityPrivileges Retrieve a privilege by name.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param privilegeName The name of the privilege to retrieve.
 @return ApiGetSecurityPrivilegesRequest
*/
func (a *SecurityManagementPrivilegesAPIService) GetSecurityPrivileges(ctx context.Context, privilegeName string) ApiGetSecurityPrivilegesRequest {
	return ApiGetSecurityPrivilegesRequest{
		ApiService: a,
		ctx: ctx,
		privilegeName: privilegeName,
	}
}

// Execute executes the request
//  @return ApiPrivilegeRequest
func (a *SecurityManagementPrivilegesAPIService) GetSecurityPrivilegesExecute(r ApiGetSecurityPrivilegesRequest) (*ApiPrivilegeRequest, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ApiPrivilegeRequest
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.GetSecurityPrivileges")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges/{privilegeName}"
	localVarPath = strings.Replace(localVarPath, "{"+"privilegeName"+"}", url.PathEscape(parameterValueToString(r.privilegeName, "privilegeName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateApplicationPrivilegeRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
	privilegeName string
	apiPrivilegeApplicationRequest *ApiPrivilegeApplicationRequest
}

// The privilege to update.
func (r ApiUpdateApplicationPrivilegeRequest) ApiPrivilegeApplicationRequest(apiPrivilegeApplicationRequest ApiPrivilegeApplicationRequest) ApiUpdateApplicationPrivilegeRequest {
	r.apiPrivilegeApplicationRequest = &apiPrivilegeApplicationRequest
	return r
}

func (r ApiUpdateApplicationPrivilegeRequest) Execute() (*http.Response, error) {
	return r.ApiService.UpdateApplicationPrivilegeExecute(r)
}

/*
UpdateApplicationPrivilege Update an application type privilege.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param privilegeName The name of the privilege to update.
 @return ApiUpdateApplicationPrivilegeRequest
*/
func (a *SecurityManagementPrivilegesAPIService) UpdateApplicationPrivilege(ctx context.Context, privilegeName string) ApiUpdateApplicationPrivilegeRequest {
	return ApiUpdateApplicationPrivilegeRequest{
		ApiService: a,
		ctx: ctx,
		privilegeName: privilegeName,
	}
}

// Execute executes the request
func (a *SecurityManagementPrivilegesAPIService) UpdateApplicationPrivilegeExecute(r ApiUpdateApplicationPrivilegeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.UpdateApplicationPrivilege")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges/application/{privilegeName}"
	localVarPath = strings.Replace(localVarPath, "{"+"privilegeName"+"}", url.PathEscape(parameterValueToString(r.privilegeName, "privilegeName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiPrivilegeApplicationRequest == nil {
		return nil, reportError("apiPrivilegeApplicationRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.apiPrivilegeApplicationRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiUpdateRepositoryAdminPrivilegeRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
	privilegeName string
	apiPrivilegeRepositoryAdminRequest *ApiPrivilegeRepositoryAdminRequest
}

// The privilege to update.
func (r ApiUpdateRepositoryAdminPrivilegeRequest) ApiPrivilegeRepositoryAdminRequest(apiPrivilegeRepositoryAdminRequest ApiPrivilegeRepositoryAdminRequest) ApiUpdateRepositoryAdminPrivilegeRequest {
	r.apiPrivilegeRepositoryAdminRequest = &apiPrivilegeRepositoryAdminRequest
	return r
}

func (r ApiUpdateRepositoryAdminPrivilegeRequest) Execute() (*http.Response, error) {
	return r.ApiService.UpdateRepositoryAdminPrivilegeExecute(r)
}

/*
UpdateRepositoryAdminPrivilege Update a repository admin type privilege.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param privilegeName The name of the privilege to update.
 @return ApiUpdateRepositoryAdminPrivilegeRequest
*/
func (a *SecurityManagementPrivilegesAPIService) UpdateRepositoryAdminPrivilege(ctx context.Context, privilegeName string) ApiUpdateRepositoryAdminPrivilegeRequest {
	return ApiUpdateRepositoryAdminPrivilegeRequest{
		ApiService: a,
		ctx: ctx,
		privilegeName: privilegeName,
	}
}

// Execute executes the request
func (a *SecurityManagementPrivilegesAPIService) UpdateRepositoryAdminPrivilegeExecute(r ApiUpdateRepositoryAdminPrivilegeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.UpdateRepositoryAdminPrivilege")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges/repository-admin/{privilegeName}"
	localVarPath = strings.Replace(localVarPath, "{"+"privilegeName"+"}", url.PathEscape(parameterValueToString(r.privilegeName, "privilegeName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiPrivilegeRepositoryAdminRequest == nil {
		return nil, reportError("apiPrivilegeRepositoryAdminRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.apiPrivilegeRepositoryAdminRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiUpdateRepositoryContentSelectorPrivilegeRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
	privilegeName string
	apiPrivilegeRepositoryContentSelectorRequest *ApiPrivilegeRepositoryContentSelectorRequest
}

// The privilege to update.
func (r ApiUpdateRepositoryContentSelectorPrivilegeRequest) ApiPrivilegeRepositoryContentSelectorRequest(apiPrivilegeRepositoryContentSelectorRequest ApiPrivilegeRepositoryContentSelectorRequest) ApiUpdateRepositoryContentSelectorPrivilegeRequest {
	r.apiPrivilegeRepositoryContentSelectorRequest = &apiPrivilegeRepositoryContentSelectorRequest
	return r
}

func (r ApiUpdateRepositoryContentSelectorPrivilegeRequest) Execute() (*http.Response, error) {
	return r.ApiService.UpdateRepositoryContentSelectorPrivilegeExecute(r)
}

/*
UpdateRepositoryContentSelectorPrivilege Update a repository content selector type privilege.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param privilegeName The name of the privilege to update.
 @return ApiUpdateRepositoryContentSelectorPrivilegeRequest
*/
func (a *SecurityManagementPrivilegesAPIService) UpdateRepositoryContentSelectorPrivilege(ctx context.Context, privilegeName string) ApiUpdateRepositoryContentSelectorPrivilegeRequest {
	return ApiUpdateRepositoryContentSelectorPrivilegeRequest{
		ApiService: a,
		ctx: ctx,
		privilegeName: privilegeName,
	}
}

// Execute executes the request
func (a *SecurityManagementPrivilegesAPIService) UpdateRepositoryContentSelectorPrivilegeExecute(r ApiUpdateRepositoryContentSelectorPrivilegeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.UpdateRepositoryContentSelectorPrivilege")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges/repository-content-selector/{privilegeName}"
	localVarPath = strings.Replace(localVarPath, "{"+"privilegeName"+"}", url.PathEscape(parameterValueToString(r.privilegeName, "privilegeName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiPrivilegeRepositoryContentSelectorRequest == nil {
		return nil, reportError("apiPrivilegeRepositoryContentSelectorRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.apiPrivilegeRepositoryContentSelectorRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiUpdateRepositoryViewPrivilegeRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
	privilegeName string
	apiPrivilegeRepositoryViewRequest *ApiPrivilegeRepositoryViewRequest
}

// The privilege to update.
func (r ApiUpdateRepositoryViewPrivilegeRequest) ApiPrivilegeRepositoryViewRequest(apiPrivilegeRepositoryViewRequest ApiPrivilegeRepositoryViewRequest) ApiUpdateRepositoryViewPrivilegeRequest {
	r.apiPrivilegeRepositoryViewRequest = &apiPrivilegeRepositoryViewRequest
	return r
}

func (r ApiUpdateRepositoryViewPrivilegeRequest) Execute() (*http.Response, error) {
	return r.ApiService.UpdateRepositoryViewPrivilegeExecute(r)
}

/*
UpdateRepositoryViewPrivilege Update a repository view type privilege.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param privilegeName The name of the privilege to update.
 @return ApiUpdateRepositoryViewPrivilegeRequest
*/
func (a *SecurityManagementPrivilegesAPIService) UpdateRepositoryViewPrivilege(ctx context.Context, privilegeName string) ApiUpdateRepositoryViewPrivilegeRequest {
	return ApiUpdateRepositoryViewPrivilegeRequest{
		ApiService: a,
		ctx: ctx,
		privilegeName: privilegeName,
	}
}

// Execute executes the request
func (a *SecurityManagementPrivilegesAPIService) UpdateRepositoryViewPrivilegeExecute(r ApiUpdateRepositoryViewPrivilegeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.UpdateRepositoryViewPrivilege")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges/repository-view/{privilegeName}"
	localVarPath = strings.Replace(localVarPath, "{"+"privilegeName"+"}", url.PathEscape(parameterValueToString(r.privilegeName, "privilegeName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiPrivilegeRepositoryViewRequest == nil {
		return nil, reportError("apiPrivilegeRepositoryViewRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.apiPrivilegeRepositoryViewRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiUpdateScriptPrivilegeRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
	privilegeName string
	apiPrivilegeScriptRequest *ApiPrivilegeScriptRequest
}

// The privilege to update.
func (r ApiUpdateScriptPrivilegeRequest) ApiPrivilegeScriptRequest(apiPrivilegeScriptRequest ApiPrivilegeScriptRequest) ApiUpdateScriptPrivilegeRequest {
	r.apiPrivilegeScriptRequest = &apiPrivilegeScriptRequest
	return r
}

func (r ApiUpdateScriptPrivilegeRequest) Execute() (*http.Response, error) {
	return r.ApiService.UpdateScriptPrivilegeExecute(r)
}

/*
UpdateScriptPrivilege Update a script type privilege.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param privilegeName The name of the privilege to update.
 @return ApiUpdateScriptPrivilegeRequest
*/
func (a *SecurityManagementPrivilegesAPIService) UpdateScriptPrivilege(ctx context.Context, privilegeName string) ApiUpdateScriptPrivilegeRequest {
	return ApiUpdateScriptPrivilegeRequest{
		ApiService: a,
		ctx: ctx,
		privilegeName: privilegeName,
	}
}

// Execute executes the request
func (a *SecurityManagementPrivilegesAPIService) UpdateScriptPrivilegeExecute(r ApiUpdateScriptPrivilegeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.UpdateScriptPrivilege")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges/script/{privilegeName}"
	localVarPath = strings.Replace(localVarPath, "{"+"privilegeName"+"}", url.PathEscape(parameterValueToString(r.privilegeName, "privilegeName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiPrivilegeScriptRequest == nil {
		return nil, reportError("apiPrivilegeScriptRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.apiPrivilegeScriptRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiUpdateWildcardPrivilegeRequest struct {
	ctx context.Context
	ApiService *SecurityManagementPrivilegesAPIService
	privilegeName string
	apiPrivilegeWildcardRequest *ApiPrivilegeWildcardRequest
}

// The privilege to update.
func (r ApiUpdateWildcardPrivilegeRequest) ApiPrivilegeWildcardRequest(apiPrivilegeWildcardRequest ApiPrivilegeWildcardRequest) ApiUpdateWildcardPrivilegeRequest {
	r.apiPrivilegeWildcardRequest = &apiPrivilegeWildcardRequest
	return r
}

func (r ApiUpdateWildcardPrivilegeRequest) Execute() (*http.Response, error) {
	return r.ApiService.UpdateWildcardPrivilegeExecute(r)
}

/*
UpdateWildcardPrivilege Update a wildcard type privilege.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param privilegeName The name of the privilege to update.
 @return ApiUpdateWildcardPrivilegeRequest
*/
func (a *SecurityManagementPrivilegesAPIService) UpdateWildcardPrivilege(ctx context.Context, privilegeName string) ApiUpdateWildcardPrivilegeRequest {
	return ApiUpdateWildcardPrivilegeRequest{
		ApiService: a,
		ctx: ctx,
		privilegeName: privilegeName,
	}
}

// Execute executes the request
func (a *SecurityManagementPrivilegesAPIService) UpdateWildcardPrivilegeExecute(r ApiUpdateWildcardPrivilegeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SecurityManagementPrivilegesAPIService.UpdateWildcardPrivilege")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/security/privileges/wildcard/{privilegeName}"
	localVarPath = strings.Replace(localVarPath, "{"+"privilegeName"+"}", url.PathEscape(parameterValueToString(r.privilegeName, "privilegeName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.apiPrivilegeWildcardRequest == nil {
		return nil, reportError("apiPrivilegeWildcardRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.apiPrivilegeWildcardRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
