/*
Sonatype Nexus Repository Manager

This documents the available APIs into [Sonatype Nexus Repository Manager](https://www.sonatype.com/products/sonatype-nexus-repository) as of version 3.93.2-01.

API version: 3.93.2-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AlpineHostedRepositoryApiRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlpineHostedRepositoryApiRequest{}

// AlpineHostedRepositoryApiRequest struct for AlpineHostedRepositoryApiRequest
type AlpineHostedRepositoryApiRequest struct {
	AlpineSigning *AlpineSigningRepositoriesAttributes `json:"alpineSigning,omitempty"`
	Cleanup *CleanupPolicyAttributes `json:"cleanup,omitempty"`
	Component *ComponentAttributes `json:"component,omitempty"`
	// A unique identifier for this repository
	Name string `json:"name" validate:"regexp=^[a-zA-Z0-9\\\\-]{1}[a-zA-Z0-9_\\\\-\\\\.]*$"`
	// Whether this repository accepts incoming requests
	Online bool `json:"online"`
	Storage HostedStorageAttributes `json:"storage"`
}

type _AlpineHostedRepositoryApiRequest AlpineHostedRepositoryApiRequest

// NewAlpineHostedRepositoryApiRequest instantiates a new AlpineHostedRepositoryApiRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlpineHostedRepositoryApiRequest(name string, online bool, storage HostedStorageAttributes) *AlpineHostedRepositoryApiRequest {
	this := AlpineHostedRepositoryApiRequest{}
	this.Name = name
	this.Online = online
	this.Storage = storage
	return &this
}

// NewAlpineHostedRepositoryApiRequestWithDefaults instantiates a new AlpineHostedRepositoryApiRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlpineHostedRepositoryApiRequestWithDefaults() *AlpineHostedRepositoryApiRequest {
	this := AlpineHostedRepositoryApiRequest{}
	return &this
}

// GetAlpineSigning returns the AlpineSigning field value if set, zero value otherwise.
func (o *AlpineHostedRepositoryApiRequest) GetAlpineSigning() AlpineSigningRepositoriesAttributes {
	if o == nil || IsNil(o.AlpineSigning) {
		var ret AlpineSigningRepositoriesAttributes
		return ret
	}
	return *o.AlpineSigning
}

// GetAlpineSigningOk returns a tuple with the AlpineSigning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlpineHostedRepositoryApiRequest) GetAlpineSigningOk() (*AlpineSigningRepositoriesAttributes, bool) {
	if o == nil || IsNil(o.AlpineSigning) {
		return nil, false
	}
	return o.AlpineSigning, true
}

// HasAlpineSigning returns a boolean if a field has been set.
func (o *AlpineHostedRepositoryApiRequest) HasAlpineSigning() bool {
	if o != nil && !IsNil(o.AlpineSigning) {
		return true
	}

	return false
}

// SetAlpineSigning gets a reference to the given AlpineSigningRepositoriesAttributes and assigns it to the AlpineSigning field.
func (o *AlpineHostedRepositoryApiRequest) SetAlpineSigning(v AlpineSigningRepositoriesAttributes) {
	o.AlpineSigning = &v
}

// GetCleanup returns the Cleanup field value if set, zero value otherwise.
func (o *AlpineHostedRepositoryApiRequest) GetCleanup() CleanupPolicyAttributes {
	if o == nil || IsNil(o.Cleanup) {
		var ret CleanupPolicyAttributes
		return ret
	}
	return *o.Cleanup
}

// GetCleanupOk returns a tuple with the Cleanup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlpineHostedRepositoryApiRequest) GetCleanupOk() (*CleanupPolicyAttributes, bool) {
	if o == nil || IsNil(o.Cleanup) {
		return nil, false
	}
	return o.Cleanup, true
}

// HasCleanup returns a boolean if a field has been set.
func (o *AlpineHostedRepositoryApiRequest) HasCleanup() bool {
	if o != nil && !IsNil(o.Cleanup) {
		return true
	}

	return false
}

// SetCleanup gets a reference to the given CleanupPolicyAttributes and assigns it to the Cleanup field.
func (o *AlpineHostedRepositoryApiRequest) SetCleanup(v CleanupPolicyAttributes) {
	o.Cleanup = &v
}

// GetComponent returns the Component field value if set, zero value otherwise.
func (o *AlpineHostedRepositoryApiRequest) GetComponent() ComponentAttributes {
	if o == nil || IsNil(o.Component) {
		var ret ComponentAttributes
		return ret
	}
	return *o.Component
}

// GetComponentOk returns a tuple with the Component field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlpineHostedRepositoryApiRequest) GetComponentOk() (*ComponentAttributes, bool) {
	if o == nil || IsNil(o.Component) {
		return nil, false
	}
	return o.Component, true
}

// HasComponent returns a boolean if a field has been set.
func (o *AlpineHostedRepositoryApiRequest) HasComponent() bool {
	if o != nil && !IsNil(o.Component) {
		return true
	}

	return false
}

// SetComponent gets a reference to the given ComponentAttributes and assigns it to the Component field.
func (o *AlpineHostedRepositoryApiRequest) SetComponent(v ComponentAttributes) {
	o.Component = &v
}

// GetName returns the Name field value
func (o *AlpineHostedRepositoryApiRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AlpineHostedRepositoryApiRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AlpineHostedRepositoryApiRequest) SetName(v string) {
	o.Name = v
}

// GetOnline returns the Online field value
func (o *AlpineHostedRepositoryApiRequest) GetOnline() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Online
}

// GetOnlineOk returns a tuple with the Online field value
// and a boolean to check if the value has been set.
func (o *AlpineHostedRepositoryApiRequest) GetOnlineOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Online, true
}

// SetOnline sets field value
func (o *AlpineHostedRepositoryApiRequest) SetOnline(v bool) {
	o.Online = v
}

// GetStorage returns the Storage field value
func (o *AlpineHostedRepositoryApiRequest) GetStorage() HostedStorageAttributes {
	if o == nil {
		var ret HostedStorageAttributes
		return ret
	}

	return o.Storage
}

// GetStorageOk returns a tuple with the Storage field value
// and a boolean to check if the value has been set.
func (o *AlpineHostedRepositoryApiRequest) GetStorageOk() (*HostedStorageAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Storage, true
}

// SetStorage sets field value
func (o *AlpineHostedRepositoryApiRequest) SetStorage(v HostedStorageAttributes) {
	o.Storage = v
}

func (o AlpineHostedRepositoryApiRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlpineHostedRepositoryApiRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AlpineSigning) {
		toSerialize["alpineSigning"] = o.AlpineSigning
	}
	if !IsNil(o.Cleanup) {
		toSerialize["cleanup"] = o.Cleanup
	}
	if !IsNil(o.Component) {
		toSerialize["component"] = o.Component
	}
	toSerialize["name"] = o.Name
	toSerialize["online"] = o.Online
	toSerialize["storage"] = o.Storage
	return toSerialize, nil
}

func (o *AlpineHostedRepositoryApiRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"online",
		"storage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlpineHostedRepositoryApiRequest := _AlpineHostedRepositoryApiRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlpineHostedRepositoryApiRequest)

	if err != nil {
		return err
	}

	*o = AlpineHostedRepositoryApiRequest(varAlpineHostedRepositoryApiRequest)

	return err
}

type NullableAlpineHostedRepositoryApiRequest struct {
	value *AlpineHostedRepositoryApiRequest
	isSet bool
}

func (v NullableAlpineHostedRepositoryApiRequest) Get() *AlpineHostedRepositoryApiRequest {
	return v.value
}

func (v *NullableAlpineHostedRepositoryApiRequest) Set(val *AlpineHostedRepositoryApiRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAlpineHostedRepositoryApiRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAlpineHostedRepositoryApiRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlpineHostedRepositoryApiRequest(val *AlpineHostedRepositoryApiRequest) *NullableAlpineHostedRepositoryApiRequest {
	return &NullableAlpineHostedRepositoryApiRequest{value: val, isSet: true}
}

func (v NullableAlpineHostedRepositoryApiRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlpineHostedRepositoryApiRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


