/*
Sonatype Nexus Repository Manager

This documents the available APIs into [Sonatype Nexus Repository Manager](https://www.sonatype.com/products/sonatype-nexus-repository) as of version 3.94.0-12.

API version: 3.94.0-12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
)

// checks if the FirewallAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FirewallAttributes{}

// FirewallAttributes struct for FirewallAttributes
type FirewallAttributes struct {
	// Firewall mode (DISABLED, AUDIT, QUARANTINE, or PCCS)
	Mode *string `json:"mode,omitempty"`
}

// NewFirewallAttributes instantiates a new FirewallAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallAttributes() *FirewallAttributes {
	this := FirewallAttributes{}
	return &this
}

// NewFirewallAttributesWithDefaults instantiates a new FirewallAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallAttributesWithDefaults() *FirewallAttributes {
	this := FirewallAttributes{}
	return &this
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *FirewallAttributes) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallAttributes) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *FirewallAttributes) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *FirewallAttributes) SetMode(v string) {
	o.Mode = &v
}

func (o FirewallAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FirewallAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	return toSerialize, nil
}

type NullableFirewallAttributes struct {
	value *FirewallAttributes
	isSet bool
}

func (v NullableFirewallAttributes) Get() *FirewallAttributes {
	return v.value
}

func (v *NullableFirewallAttributes) Set(val *FirewallAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallAttributes(val *FirewallAttributes) *NullableFirewallAttributes {
	return &NullableFirewallAttributes{value: val, isSet: true}
}

func (v NullableFirewallAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


