/*
Sonatype Nexus Repository Manager

This documents the available APIs into [Sonatype Nexus Repository Manager](https://www.sonatype.com/products/sonatype-nexus-repository) as of version 3.94.0-12.

API version: 3.94.0-12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OciAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OciAttributes{}

// OciAttributes struct for OciAttributes
type OciAttributes struct {
	// Whether to force authentication (OCI Bearer Token Realm required if false)
	ForceBasicAuth bool `json:"forceBasicAuth"`
	// Create an HTTP connector at specified port
	HttpPort *int32 `json:"httpPort,omitempty"`
	// Create an HTTPS connector at specified port
	HttpsPort *int32 `json:"httpsPort,omitempty"`
	// Allows to use repository name in OCI image paths
	PathEnabled *bool `json:"pathEnabled,omitempty"`
	// Allows to use subdomain
	Subdomain *string `json:"subdomain,omitempty"`
	// Whether to allow clients to use the V1 API to interact with this repository
	V1Enabled bool `json:"v1Enabled"`
}

type _OciAttributes OciAttributes

// NewOciAttributes instantiates a new OciAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOciAttributes(forceBasicAuth bool, v1Enabled bool) *OciAttributes {
	this := OciAttributes{}
	this.ForceBasicAuth = forceBasicAuth
	this.V1Enabled = v1Enabled
	return &this
}

// NewOciAttributesWithDefaults instantiates a new OciAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOciAttributesWithDefaults() *OciAttributes {
	this := OciAttributes{}
	return &this
}

// GetForceBasicAuth returns the ForceBasicAuth field value
func (o *OciAttributes) GetForceBasicAuth() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ForceBasicAuth
}

// GetForceBasicAuthOk returns a tuple with the ForceBasicAuth field value
// and a boolean to check if the value has been set.
func (o *OciAttributes) GetForceBasicAuthOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ForceBasicAuth, true
}

// SetForceBasicAuth sets field value
func (o *OciAttributes) SetForceBasicAuth(v bool) {
	o.ForceBasicAuth = v
}

// GetHttpPort returns the HttpPort field value if set, zero value otherwise.
func (o *OciAttributes) GetHttpPort() int32 {
	if o == nil || IsNil(o.HttpPort) {
		var ret int32
		return ret
	}
	return *o.HttpPort
}

// GetHttpPortOk returns a tuple with the HttpPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OciAttributes) GetHttpPortOk() (*int32, bool) {
	if o == nil || IsNil(o.HttpPort) {
		return nil, false
	}
	return o.HttpPort, true
}

// HasHttpPort returns a boolean if a field has been set.
func (o *OciAttributes) HasHttpPort() bool {
	if o != nil && !IsNil(o.HttpPort) {
		return true
	}

	return false
}

// SetHttpPort gets a reference to the given int32 and assigns it to the HttpPort field.
func (o *OciAttributes) SetHttpPort(v int32) {
	o.HttpPort = &v
}

// GetHttpsPort returns the HttpsPort field value if set, zero value otherwise.
func (o *OciAttributes) GetHttpsPort() int32 {
	if o == nil || IsNil(o.HttpsPort) {
		var ret int32
		return ret
	}
	return *o.HttpsPort
}

// GetHttpsPortOk returns a tuple with the HttpsPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OciAttributes) GetHttpsPortOk() (*int32, bool) {
	if o == nil || IsNil(o.HttpsPort) {
		return nil, false
	}
	return o.HttpsPort, true
}

// HasHttpsPort returns a boolean if a field has been set.
func (o *OciAttributes) HasHttpsPort() bool {
	if o != nil && !IsNil(o.HttpsPort) {
		return true
	}

	return false
}

// SetHttpsPort gets a reference to the given int32 and assigns it to the HttpsPort field.
func (o *OciAttributes) SetHttpsPort(v int32) {
	o.HttpsPort = &v
}

// GetPathEnabled returns the PathEnabled field value if set, zero value otherwise.
func (o *OciAttributes) GetPathEnabled() bool {
	if o == nil || IsNil(o.PathEnabled) {
		var ret bool
		return ret
	}
	return *o.PathEnabled
}

// GetPathEnabledOk returns a tuple with the PathEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OciAttributes) GetPathEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.PathEnabled) {
		return nil, false
	}
	return o.PathEnabled, true
}

// HasPathEnabled returns a boolean if a field has been set.
func (o *OciAttributes) HasPathEnabled() bool {
	if o != nil && !IsNil(o.PathEnabled) {
		return true
	}

	return false
}

// SetPathEnabled gets a reference to the given bool and assigns it to the PathEnabled field.
func (o *OciAttributes) SetPathEnabled(v bool) {
	o.PathEnabled = &v
}

// GetSubdomain returns the Subdomain field value if set, zero value otherwise.
func (o *OciAttributes) GetSubdomain() string {
	if o == nil || IsNil(o.Subdomain) {
		var ret string
		return ret
	}
	return *o.Subdomain
}

// GetSubdomainOk returns a tuple with the Subdomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OciAttributes) GetSubdomainOk() (*string, bool) {
	if o == nil || IsNil(o.Subdomain) {
		return nil, false
	}
	return o.Subdomain, true
}

// HasSubdomain returns a boolean if a field has been set.
func (o *OciAttributes) HasSubdomain() bool {
	if o != nil && !IsNil(o.Subdomain) {
		return true
	}

	return false
}

// SetSubdomain gets a reference to the given string and assigns it to the Subdomain field.
func (o *OciAttributes) SetSubdomain(v string) {
	o.Subdomain = &v
}

// GetV1Enabled returns the V1Enabled field value
func (o *OciAttributes) GetV1Enabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.V1Enabled
}

// GetV1EnabledOk returns a tuple with the V1Enabled field value
// and a boolean to check if the value has been set.
func (o *OciAttributes) GetV1EnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.V1Enabled, true
}

// SetV1Enabled sets field value
func (o *OciAttributes) SetV1Enabled(v bool) {
	o.V1Enabled = v
}

func (o OciAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OciAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["forceBasicAuth"] = o.ForceBasicAuth
	if !IsNil(o.HttpPort) {
		toSerialize["httpPort"] = o.HttpPort
	}
	if !IsNil(o.HttpsPort) {
		toSerialize["httpsPort"] = o.HttpsPort
	}
	if !IsNil(o.PathEnabled) {
		toSerialize["pathEnabled"] = o.PathEnabled
	}
	if !IsNil(o.Subdomain) {
		toSerialize["subdomain"] = o.Subdomain
	}
	toSerialize["v1Enabled"] = o.V1Enabled
	return toSerialize, nil
}

func (o *OciAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"forceBasicAuth",
		"v1Enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOciAttributes := _OciAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOciAttributes)

	if err != nil {
		return err
	}

	*o = OciAttributes(varOciAttributes)

	return err
}

type NullableOciAttributes struct {
	value *OciAttributes
	isSet bool
}

func (v NullableOciAttributes) Get() *OciAttributes {
	return v.value
}

func (v *NullableOciAttributes) Set(val *OciAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableOciAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableOciAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOciAttributes(val *OciAttributes) *NullableOciAttributes {
	return &NullableOciAttributes{value: val, isSet: true}
}

func (v NullableOciAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOciAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


