/*
Sonatype Nexus Repository Manager

This documents the available APIs into [Sonatype Nexus Repository Manager](https://www.sonatype.com/products/sonatype-nexus-repository) as of version 3.96.0-09.

API version: 3.96.0-09
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v395

import (
	"encoding/json"
)

// checks if the PageSamlUserXO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PageSamlUserXO{}

// PageSamlUserXO struct for PageSamlUserXO
type PageSamlUserXO struct {
	ContinuationToken *string `json:"continuationToken,omitempty"`
	Items []SamlUserXO `json:"items,omitempty"`
}

// NewPageSamlUserXO instantiates a new PageSamlUserXO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPageSamlUserXO() *PageSamlUserXO {
	this := PageSamlUserXO{}
	return &this
}

// NewPageSamlUserXOWithDefaults instantiates a new PageSamlUserXO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPageSamlUserXOWithDefaults() *PageSamlUserXO {
	this := PageSamlUserXO{}
	return &this
}

// GetContinuationToken returns the ContinuationToken field value if set, zero value otherwise.
func (o *PageSamlUserXO) GetContinuationToken() string {
	if o == nil || IsNil(o.ContinuationToken) {
		var ret string
		return ret
	}
	return *o.ContinuationToken
}

// GetContinuationTokenOk returns a tuple with the ContinuationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageSamlUserXO) GetContinuationTokenOk() (*string, bool) {
	if o == nil || IsNil(o.ContinuationToken) {
		return nil, false
	}
	return o.ContinuationToken, true
}

// HasContinuationToken returns a boolean if a field has been set.
func (o *PageSamlUserXO) HasContinuationToken() bool {
	if o != nil && !IsNil(o.ContinuationToken) {
		return true
	}

	return false
}

// SetContinuationToken gets a reference to the given string and assigns it to the ContinuationToken field.
func (o *PageSamlUserXO) SetContinuationToken(v string) {
	o.ContinuationToken = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PageSamlUserXO) GetItems() []SamlUserXO {
	if o == nil || IsNil(o.Items) {
		var ret []SamlUserXO
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageSamlUserXO) GetItemsOk() ([]SamlUserXO, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PageSamlUserXO) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []SamlUserXO and assigns it to the Items field.
func (o *PageSamlUserXO) SetItems(v []SamlUserXO) {
	o.Items = v
}

func (o PageSamlUserXO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PageSamlUserXO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContinuationToken) {
		toSerialize["continuationToken"] = o.ContinuationToken
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullablePageSamlUserXO struct {
	value *PageSamlUserXO
	isSet bool
}

func (v NullablePageSamlUserXO) Get() *PageSamlUserXO {
	return v.value
}

func (v *NullablePageSamlUserXO) Set(val *PageSamlUserXO) {
	v.value = val
	v.isSet = true
}

func (v NullablePageSamlUserXO) IsSet() bool {
	return v.isSet
}

func (v *NullablePageSamlUserXO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePageSamlUserXO(val *PageSamlUserXO) *NullablePageSamlUserXO {
	return &NullablePageSamlUserXO{value: val, isSet: true}
}

func (v NullablePageSamlUserXO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePageSamlUserXO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


