/*
Sonatype Nexus Repository Manager

This documents the available APIs into [Sonatype Nexus Repository Manager](https://www.sonatype.com/products/sonatype-nexus-repository) as of version 3.93.2-01.

API version: 3.93.2-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"time"
)

// checks if the TaskXO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskXO{}

// TaskXO Represents a task in Nexus Repository Manager
type TaskXO struct {
	// Email address to send notifications to
	AlertEmail *string `json:"alertEmail,omitempty"`
	// Cron expression for advanced schedules
	CronExpression *string `json:"cronExpression,omitempty"`
	// The current state of the task
	CurrentState *string `json:"currentState,omitempty"`
	// Whether the task is enabled
	Enabled *bool `json:"enabled,omitempty"`
	// The unique identifier of the task
	Id *string `json:"id,omitempty"`
	// The last run start time (ISO 8601 format)
	LastRun *time.Time `json:"lastRun,omitempty"`
	// The result of the last run
	LastRunResult *string `json:"lastRunResult,omitempty"`
	// A human-readable message describing the task
	Message *string `json:"message,omitempty"`
	// The name of the task
	Name *string `json:"name,omitempty"`
	// The next scheduled run time (ISO 8601 format)
	NextRun *time.Time `json:"nextRun,omitempty"`
	// Condition for sending notifications
	NotificationCondition *string `json:"notificationCondition,omitempty"`
	// Task-specific configuration properties
	Properties *map[string]string `json:"properties,omitempty"`
	// Days of the week/month for recurring schedules (1=Sunday, 7=Saturday, 999=last day of month)
	RecurringDays []int32 `json:"recurringDays,omitempty"`
	// The schedule type
	Schedule *string `json:"schedule,omitempty"`
	// The start date for scheduled tasks (ISO 8601 format)
	StartDate *time.Time `json:"startDate,omitempty"`
	// Time zone offset for cron schedules
	TimeZoneOffset *string `json:"timeZoneOffset,omitempty"`
	// The type identifier of the task
	Type *string `json:"type,omitempty"`
}

// NewTaskXO instantiates a new TaskXO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskXO() *TaskXO {
	this := TaskXO{}
	return &this
}

// NewTaskXOWithDefaults instantiates a new TaskXO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskXOWithDefaults() *TaskXO {
	this := TaskXO{}
	return &this
}

// GetAlertEmail returns the AlertEmail field value if set, zero value otherwise.
func (o *TaskXO) GetAlertEmail() string {
	if o == nil || IsNil(o.AlertEmail) {
		var ret string
		return ret
	}
	return *o.AlertEmail
}

// GetAlertEmailOk returns a tuple with the AlertEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetAlertEmailOk() (*string, bool) {
	if o == nil || IsNil(o.AlertEmail) {
		return nil, false
	}
	return o.AlertEmail, true
}

// HasAlertEmail returns a boolean if a field has been set.
func (o *TaskXO) HasAlertEmail() bool {
	if o != nil && !IsNil(o.AlertEmail) {
		return true
	}

	return false
}

// SetAlertEmail gets a reference to the given string and assigns it to the AlertEmail field.
func (o *TaskXO) SetAlertEmail(v string) {
	o.AlertEmail = &v
}

// GetCronExpression returns the CronExpression field value if set, zero value otherwise.
func (o *TaskXO) GetCronExpression() string {
	if o == nil || IsNil(o.CronExpression) {
		var ret string
		return ret
	}
	return *o.CronExpression
}

// GetCronExpressionOk returns a tuple with the CronExpression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetCronExpressionOk() (*string, bool) {
	if o == nil || IsNil(o.CronExpression) {
		return nil, false
	}
	return o.CronExpression, true
}

// HasCronExpression returns a boolean if a field has been set.
func (o *TaskXO) HasCronExpression() bool {
	if o != nil && !IsNil(o.CronExpression) {
		return true
	}

	return false
}

// SetCronExpression gets a reference to the given string and assigns it to the CronExpression field.
func (o *TaskXO) SetCronExpression(v string) {
	o.CronExpression = &v
}

// GetCurrentState returns the CurrentState field value if set, zero value otherwise.
func (o *TaskXO) GetCurrentState() string {
	if o == nil || IsNil(o.CurrentState) {
		var ret string
		return ret
	}
	return *o.CurrentState
}

// GetCurrentStateOk returns a tuple with the CurrentState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetCurrentStateOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentState) {
		return nil, false
	}
	return o.CurrentState, true
}

// HasCurrentState returns a boolean if a field has been set.
func (o *TaskXO) HasCurrentState() bool {
	if o != nil && !IsNil(o.CurrentState) {
		return true
	}

	return false
}

// SetCurrentState gets a reference to the given string and assigns it to the CurrentState field.
func (o *TaskXO) SetCurrentState(v string) {
	o.CurrentState = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *TaskXO) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *TaskXO) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *TaskXO) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TaskXO) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TaskXO) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TaskXO) SetId(v string) {
	o.Id = &v
}

// GetLastRun returns the LastRun field value if set, zero value otherwise.
func (o *TaskXO) GetLastRun() time.Time {
	if o == nil || IsNil(o.LastRun) {
		var ret time.Time
		return ret
	}
	return *o.LastRun
}

// GetLastRunOk returns a tuple with the LastRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetLastRunOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastRun) {
		return nil, false
	}
	return o.LastRun, true
}

// HasLastRun returns a boolean if a field has been set.
func (o *TaskXO) HasLastRun() bool {
	if o != nil && !IsNil(o.LastRun) {
		return true
	}

	return false
}

// SetLastRun gets a reference to the given time.Time and assigns it to the LastRun field.
func (o *TaskXO) SetLastRun(v time.Time) {
	o.LastRun = &v
}

// GetLastRunResult returns the LastRunResult field value if set, zero value otherwise.
func (o *TaskXO) GetLastRunResult() string {
	if o == nil || IsNil(o.LastRunResult) {
		var ret string
		return ret
	}
	return *o.LastRunResult
}

// GetLastRunResultOk returns a tuple with the LastRunResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetLastRunResultOk() (*string, bool) {
	if o == nil || IsNil(o.LastRunResult) {
		return nil, false
	}
	return o.LastRunResult, true
}

// HasLastRunResult returns a boolean if a field has been set.
func (o *TaskXO) HasLastRunResult() bool {
	if o != nil && !IsNil(o.LastRunResult) {
		return true
	}

	return false
}

// SetLastRunResult gets a reference to the given string and assigns it to the LastRunResult field.
func (o *TaskXO) SetLastRunResult(v string) {
	o.LastRunResult = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *TaskXO) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *TaskXO) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *TaskXO) SetMessage(v string) {
	o.Message = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TaskXO) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TaskXO) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TaskXO) SetName(v string) {
	o.Name = &v
}

// GetNextRun returns the NextRun field value if set, zero value otherwise.
func (o *TaskXO) GetNextRun() time.Time {
	if o == nil || IsNil(o.NextRun) {
		var ret time.Time
		return ret
	}
	return *o.NextRun
}

// GetNextRunOk returns a tuple with the NextRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetNextRunOk() (*time.Time, bool) {
	if o == nil || IsNil(o.NextRun) {
		return nil, false
	}
	return o.NextRun, true
}

// HasNextRun returns a boolean if a field has been set.
func (o *TaskXO) HasNextRun() bool {
	if o != nil && !IsNil(o.NextRun) {
		return true
	}

	return false
}

// SetNextRun gets a reference to the given time.Time and assigns it to the NextRun field.
func (o *TaskXO) SetNextRun(v time.Time) {
	o.NextRun = &v
}

// GetNotificationCondition returns the NotificationCondition field value if set, zero value otherwise.
func (o *TaskXO) GetNotificationCondition() string {
	if o == nil || IsNil(o.NotificationCondition) {
		var ret string
		return ret
	}
	return *o.NotificationCondition
}

// GetNotificationConditionOk returns a tuple with the NotificationCondition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetNotificationConditionOk() (*string, bool) {
	if o == nil || IsNil(o.NotificationCondition) {
		return nil, false
	}
	return o.NotificationCondition, true
}

// HasNotificationCondition returns a boolean if a field has been set.
func (o *TaskXO) HasNotificationCondition() bool {
	if o != nil && !IsNil(o.NotificationCondition) {
		return true
	}

	return false
}

// SetNotificationCondition gets a reference to the given string and assigns it to the NotificationCondition field.
func (o *TaskXO) SetNotificationCondition(v string) {
	o.NotificationCondition = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *TaskXO) GetProperties() map[string]string {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]string
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetPropertiesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *TaskXO) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]string and assigns it to the Properties field.
func (o *TaskXO) SetProperties(v map[string]string) {
	o.Properties = &v
}

// GetRecurringDays returns the RecurringDays field value if set, zero value otherwise.
func (o *TaskXO) GetRecurringDays() []int32 {
	if o == nil || IsNil(o.RecurringDays) {
		var ret []int32
		return ret
	}
	return o.RecurringDays
}

// GetRecurringDaysOk returns a tuple with the RecurringDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetRecurringDaysOk() ([]int32, bool) {
	if o == nil || IsNil(o.RecurringDays) {
		return nil, false
	}
	return o.RecurringDays, true
}

// HasRecurringDays returns a boolean if a field has been set.
func (o *TaskXO) HasRecurringDays() bool {
	if o != nil && !IsNil(o.RecurringDays) {
		return true
	}

	return false
}

// SetRecurringDays gets a reference to the given []int32 and assigns it to the RecurringDays field.
func (o *TaskXO) SetRecurringDays(v []int32) {
	o.RecurringDays = v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *TaskXO) GetSchedule() string {
	if o == nil || IsNil(o.Schedule) {
		var ret string
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetScheduleOk() (*string, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *TaskXO) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given string and assigns it to the Schedule field.
func (o *TaskXO) SetSchedule(v string) {
	o.Schedule = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *TaskXO) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *TaskXO) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *TaskXO) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetTimeZoneOffset returns the TimeZoneOffset field value if set, zero value otherwise.
func (o *TaskXO) GetTimeZoneOffset() string {
	if o == nil || IsNil(o.TimeZoneOffset) {
		var ret string
		return ret
	}
	return *o.TimeZoneOffset
}

// GetTimeZoneOffsetOk returns a tuple with the TimeZoneOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetTimeZoneOffsetOk() (*string, bool) {
	if o == nil || IsNil(o.TimeZoneOffset) {
		return nil, false
	}
	return o.TimeZoneOffset, true
}

// HasTimeZoneOffset returns a boolean if a field has been set.
func (o *TaskXO) HasTimeZoneOffset() bool {
	if o != nil && !IsNil(o.TimeZoneOffset) {
		return true
	}

	return false
}

// SetTimeZoneOffset gets a reference to the given string and assigns it to the TimeZoneOffset field.
func (o *TaskXO) SetTimeZoneOffset(v string) {
	o.TimeZoneOffset = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TaskXO) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskXO) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TaskXO) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TaskXO) SetType(v string) {
	o.Type = &v
}

func (o TaskXO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskXO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AlertEmail) {
		toSerialize["alertEmail"] = o.AlertEmail
	}
	if !IsNil(o.CronExpression) {
		toSerialize["cronExpression"] = o.CronExpression
	}
	if !IsNil(o.CurrentState) {
		toSerialize["currentState"] = o.CurrentState
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LastRun) {
		toSerialize["lastRun"] = o.LastRun
	}
	if !IsNil(o.LastRunResult) {
		toSerialize["lastRunResult"] = o.LastRunResult
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NextRun) {
		toSerialize["nextRun"] = o.NextRun
	}
	if !IsNil(o.NotificationCondition) {
		toSerialize["notificationCondition"] = o.NotificationCondition
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.RecurringDays) {
		toSerialize["recurringDays"] = o.RecurringDays
	}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	if !IsNil(o.TimeZoneOffset) {
		toSerialize["timeZoneOffset"] = o.TimeZoneOffset
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableTaskXO struct {
	value *TaskXO
	isSet bool
}

func (v NullableTaskXO) Get() *TaskXO {
	return v.value
}

func (v *NullableTaskXO) Set(val *TaskXO) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskXO) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskXO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskXO(val *TaskXO) *NullableTaskXO {
	return &NullableTaskXO{value: val, isSet: true}
}

func (v NullableTaskXO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskXO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


