/*
Sonatype Nexus Repository Manager

This documents the available APIs into [Sonatype Nexus Repository Manager](https://www.sonatype.com/products/sonatype-nexus-repository) as of version 3.96.0-09.

API version: 3.96.0-09
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v395

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComposerGroupRepositoryApiRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComposerGroupRepositoryApiRequest{}

// ComposerGroupRepositoryApiRequest struct for ComposerGroupRepositoryApiRequest
type ComposerGroupRepositoryApiRequest struct {
	Group GroupAttributes `json:"group"`
	// A unique identifier for this repository
	Name string `json:"name" validate:"regexp=^[a-zA-Z0-9\\\\-]{1}[a-zA-Z0-9_\\\\-\\\\.]*$"`
	// Whether this repository accepts incoming requests
	Online bool `json:"online"`
	Storage StorageAttributes `json:"storage"`
}

type _ComposerGroupRepositoryApiRequest ComposerGroupRepositoryApiRequest

// NewComposerGroupRepositoryApiRequest instantiates a new ComposerGroupRepositoryApiRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComposerGroupRepositoryApiRequest(group GroupAttributes, name string, online bool, storage StorageAttributes) *ComposerGroupRepositoryApiRequest {
	this := ComposerGroupRepositoryApiRequest{}
	this.Group = group
	this.Name = name
	this.Online = online
	this.Storage = storage
	return &this
}

// NewComposerGroupRepositoryApiRequestWithDefaults instantiates a new ComposerGroupRepositoryApiRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComposerGroupRepositoryApiRequestWithDefaults() *ComposerGroupRepositoryApiRequest {
	this := ComposerGroupRepositoryApiRequest{}
	return &this
}

// GetGroup returns the Group field value
func (o *ComposerGroupRepositoryApiRequest) GetGroup() GroupAttributes {
	if o == nil {
		var ret GroupAttributes
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *ComposerGroupRepositoryApiRequest) GetGroupOk() (*GroupAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *ComposerGroupRepositoryApiRequest) SetGroup(v GroupAttributes) {
	o.Group = v
}

// GetName returns the Name field value
func (o *ComposerGroupRepositoryApiRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ComposerGroupRepositoryApiRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ComposerGroupRepositoryApiRequest) SetName(v string) {
	o.Name = v
}

// GetOnline returns the Online field value
func (o *ComposerGroupRepositoryApiRequest) GetOnline() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Online
}

// GetOnlineOk returns a tuple with the Online field value
// and a boolean to check if the value has been set.
func (o *ComposerGroupRepositoryApiRequest) GetOnlineOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Online, true
}

// SetOnline sets field value
func (o *ComposerGroupRepositoryApiRequest) SetOnline(v bool) {
	o.Online = v
}

// GetStorage returns the Storage field value
func (o *ComposerGroupRepositoryApiRequest) GetStorage() StorageAttributes {
	if o == nil {
		var ret StorageAttributes
		return ret
	}

	return o.Storage
}

// GetStorageOk returns a tuple with the Storage field value
// and a boolean to check if the value has been set.
func (o *ComposerGroupRepositoryApiRequest) GetStorageOk() (*StorageAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Storage, true
}

// SetStorage sets field value
func (o *ComposerGroupRepositoryApiRequest) SetStorage(v StorageAttributes) {
	o.Storage = v
}

func (o ComposerGroupRepositoryApiRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComposerGroupRepositoryApiRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["group"] = o.Group
	toSerialize["name"] = o.Name
	toSerialize["online"] = o.Online
	toSerialize["storage"] = o.Storage
	return toSerialize, nil
}

func (o *ComposerGroupRepositoryApiRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"group",
		"name",
		"online",
		"storage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComposerGroupRepositoryApiRequest := _ComposerGroupRepositoryApiRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComposerGroupRepositoryApiRequest)

	if err != nil {
		return err
	}

	*o = ComposerGroupRepositoryApiRequest(varComposerGroupRepositoryApiRequest)

	return err
}

type NullableComposerGroupRepositoryApiRequest struct {
	value *ComposerGroupRepositoryApiRequest
	isSet bool
}

func (v NullableComposerGroupRepositoryApiRequest) Get() *ComposerGroupRepositoryApiRequest {
	return v.value
}

func (v *NullableComposerGroupRepositoryApiRequest) Set(val *ComposerGroupRepositoryApiRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableComposerGroupRepositoryApiRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableComposerGroupRepositoryApiRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComposerGroupRepositoryApiRequest(val *ComposerGroupRepositoryApiRequest) *NullableComposerGroupRepositoryApiRequest {
	return &NullableComposerGroupRepositoryApiRequest{value: val, isSet: true}
}

func (v NullableComposerGroupRepositoryApiRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComposerGroupRepositoryApiRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


