/*
Sonatype Nexus Repository Manager

This documents the available APIs into [Sonatype Nexus Repository Manager](https://www.sonatype.com/products/sonatype-nexus-repository) as of version 3.94.0-12.

API version: 3.94.0-12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HttpClientConnectionAuthenticationAttributesWithPreemptive type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HttpClientConnectionAuthenticationAttributesWithPreemptive{}

// HttpClientConnectionAuthenticationAttributesWithPreemptive struct for HttpClientConnectionAuthenticationAttributesWithPreemptive
type HttpClientConnectionAuthenticationAttributesWithPreemptive struct {
	BearerToken *string `json:"bearerToken,omitempty"`
	NtlmDomain *string `json:"ntlmDomain,omitempty"`
	NtlmHost *string `json:"ntlmHost,omitempty"`
	Password *string `json:"password,omitempty"`
	// Whether to use pre-emptive authentication. Use with caution. Defaults to false.
	Preemptive *bool `json:"preemptive,omitempty"`
	// Authentication type
	Type string `json:"type"`
	Username *string `json:"username,omitempty"`
}

type _HttpClientConnectionAuthenticationAttributesWithPreemptive HttpClientConnectionAuthenticationAttributesWithPreemptive

// NewHttpClientConnectionAuthenticationAttributesWithPreemptive instantiates a new HttpClientConnectionAuthenticationAttributesWithPreemptive object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttpClientConnectionAuthenticationAttributesWithPreemptive(type_ string) *HttpClientConnectionAuthenticationAttributesWithPreemptive {
	this := HttpClientConnectionAuthenticationAttributesWithPreemptive{}
	this.Type = type_
	return &this
}

// NewHttpClientConnectionAuthenticationAttributesWithPreemptiveWithDefaults instantiates a new HttpClientConnectionAuthenticationAttributesWithPreemptive object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttpClientConnectionAuthenticationAttributesWithPreemptiveWithDefaults() *HttpClientConnectionAuthenticationAttributesWithPreemptive {
	this := HttpClientConnectionAuthenticationAttributesWithPreemptive{}
	return &this
}

// GetBearerToken returns the BearerToken field value if set, zero value otherwise.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) GetBearerToken() string {
	if o == nil || IsNil(o.BearerToken) {
		var ret string
		return ret
	}
	return *o.BearerToken
}

// GetBearerTokenOk returns a tuple with the BearerToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) GetBearerTokenOk() (*string, bool) {
	if o == nil || IsNil(o.BearerToken) {
		return nil, false
	}
	return o.BearerToken, true
}

// HasBearerToken returns a boolean if a field has been set.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) HasBearerToken() bool {
	if o != nil && !IsNil(o.BearerToken) {
		return true
	}

	return false
}

// SetBearerToken gets a reference to the given string and assigns it to the BearerToken field.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) SetBearerToken(v string) {
	o.BearerToken = &v
}

// GetNtlmDomain returns the NtlmDomain field value if set, zero value otherwise.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) GetNtlmDomain() string {
	if o == nil || IsNil(o.NtlmDomain) {
		var ret string
		return ret
	}
	return *o.NtlmDomain
}

// GetNtlmDomainOk returns a tuple with the NtlmDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) GetNtlmDomainOk() (*string, bool) {
	if o == nil || IsNil(o.NtlmDomain) {
		return nil, false
	}
	return o.NtlmDomain, true
}

// HasNtlmDomain returns a boolean if a field has been set.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) HasNtlmDomain() bool {
	if o != nil && !IsNil(o.NtlmDomain) {
		return true
	}

	return false
}

// SetNtlmDomain gets a reference to the given string and assigns it to the NtlmDomain field.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) SetNtlmDomain(v string) {
	o.NtlmDomain = &v
}

// GetNtlmHost returns the NtlmHost field value if set, zero value otherwise.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) GetNtlmHost() string {
	if o == nil || IsNil(o.NtlmHost) {
		var ret string
		return ret
	}
	return *o.NtlmHost
}

// GetNtlmHostOk returns a tuple with the NtlmHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) GetNtlmHostOk() (*string, bool) {
	if o == nil || IsNil(o.NtlmHost) {
		return nil, false
	}
	return o.NtlmHost, true
}

// HasNtlmHost returns a boolean if a field has been set.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) HasNtlmHost() bool {
	if o != nil && !IsNil(o.NtlmHost) {
		return true
	}

	return false
}

// SetNtlmHost gets a reference to the given string and assigns it to the NtlmHost field.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) SetNtlmHost(v string) {
	o.NtlmHost = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) SetPassword(v string) {
	o.Password = &v
}

// GetPreemptive returns the Preemptive field value if set, zero value otherwise.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) GetPreemptive() bool {
	if o == nil || IsNil(o.Preemptive) {
		var ret bool
		return ret
	}
	return *o.Preemptive
}

// GetPreemptiveOk returns a tuple with the Preemptive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) GetPreemptiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Preemptive) {
		return nil, false
	}
	return o.Preemptive, true
}

// HasPreemptive returns a boolean if a field has been set.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) HasPreemptive() bool {
	if o != nil && !IsNil(o.Preemptive) {
		return true
	}

	return false
}

// SetPreemptive gets a reference to the given bool and assigns it to the Preemptive field.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) SetPreemptive(v bool) {
	o.Preemptive = &v
}

// GetType returns the Type field value
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) SetType(v string) {
	o.Type = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) SetUsername(v string) {
	o.Username = &v
}

func (o HttpClientConnectionAuthenticationAttributesWithPreemptive) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HttpClientConnectionAuthenticationAttributesWithPreemptive) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BearerToken) {
		toSerialize["bearerToken"] = o.BearerToken
	}
	if !IsNil(o.NtlmDomain) {
		toSerialize["ntlmDomain"] = o.NtlmDomain
	}
	if !IsNil(o.NtlmHost) {
		toSerialize["ntlmHost"] = o.NtlmHost
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.Preemptive) {
		toSerialize["preemptive"] = o.Preemptive
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

func (o *HttpClientConnectionAuthenticationAttributesWithPreemptive) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHttpClientConnectionAuthenticationAttributesWithPreemptive := _HttpClientConnectionAuthenticationAttributesWithPreemptive{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHttpClientConnectionAuthenticationAttributesWithPreemptive)

	if err != nil {
		return err
	}

	*o = HttpClientConnectionAuthenticationAttributesWithPreemptive(varHttpClientConnectionAuthenticationAttributesWithPreemptive)

	return err
}

type NullableHttpClientConnectionAuthenticationAttributesWithPreemptive struct {
	value *HttpClientConnectionAuthenticationAttributesWithPreemptive
	isSet bool
}

func (v NullableHttpClientConnectionAuthenticationAttributesWithPreemptive) Get() *HttpClientConnectionAuthenticationAttributesWithPreemptive {
	return v.value
}

func (v *NullableHttpClientConnectionAuthenticationAttributesWithPreemptive) Set(val *HttpClientConnectionAuthenticationAttributesWithPreemptive) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpClientConnectionAuthenticationAttributesWithPreemptive) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpClientConnectionAuthenticationAttributesWithPreemptive) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpClientConnectionAuthenticationAttributesWithPreemptive(val *HttpClientConnectionAuthenticationAttributesWithPreemptive) *NullableHttpClientConnectionAuthenticationAttributesWithPreemptive {
	return &NullableHttpClientConnectionAuthenticationAttributesWithPreemptive{value: val, isSet: true}
}

func (v NullableHttpClientConnectionAuthenticationAttributesWithPreemptive) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpClientConnectionAuthenticationAttributesWithPreemptive) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


