/*
Sonatype Nexus Repository Manager

This documents the available APIs into [Sonatype Nexus Repository Manager](https://www.sonatype.com/products/sonatype-nexus-repository) as of version 3.88.0-08.

API version: 3.88.0-08
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RawGroupRepositoryApiRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RawGroupRepositoryApiRequest{}

// RawGroupRepositoryApiRequest struct for RawGroupRepositoryApiRequest
type RawGroupRepositoryApiRequest struct {
	Group GroupAttributes `json:"group"`
	// A unique identifier for this repository
	Name string `json:"name" validate:"regexp=^[a-zA-Z0-9\\\\-]{1}[a-zA-Z0-9_\\\\-\\\\.]*$"`
	// Whether this repository accepts incoming requests
	Online bool `json:"online"`
	Raw *RawAttributes `json:"raw,omitempty"`
	Storage StorageAttributes `json:"storage"`
}

type _RawGroupRepositoryApiRequest RawGroupRepositoryApiRequest

// NewRawGroupRepositoryApiRequest instantiates a new RawGroupRepositoryApiRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRawGroupRepositoryApiRequest(group GroupAttributes, name string, online bool, storage StorageAttributes) *RawGroupRepositoryApiRequest {
	this := RawGroupRepositoryApiRequest{}
	this.Group = group
	this.Name = name
	this.Online = online
	this.Storage = storage
	return &this
}

// NewRawGroupRepositoryApiRequestWithDefaults instantiates a new RawGroupRepositoryApiRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRawGroupRepositoryApiRequestWithDefaults() *RawGroupRepositoryApiRequest {
	this := RawGroupRepositoryApiRequest{}
	return &this
}

// GetGroup returns the Group field value
func (o *RawGroupRepositoryApiRequest) GetGroup() GroupAttributes {
	if o == nil {
		var ret GroupAttributes
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *RawGroupRepositoryApiRequest) GetGroupOk() (*GroupAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *RawGroupRepositoryApiRequest) SetGroup(v GroupAttributes) {
	o.Group = v
}

// GetName returns the Name field value
func (o *RawGroupRepositoryApiRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RawGroupRepositoryApiRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RawGroupRepositoryApiRequest) SetName(v string) {
	o.Name = v
}

// GetOnline returns the Online field value
func (o *RawGroupRepositoryApiRequest) GetOnline() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Online
}

// GetOnlineOk returns a tuple with the Online field value
// and a boolean to check if the value has been set.
func (o *RawGroupRepositoryApiRequest) GetOnlineOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Online, true
}

// SetOnline sets field value
func (o *RawGroupRepositoryApiRequest) SetOnline(v bool) {
	o.Online = v
}

// GetRaw returns the Raw field value if set, zero value otherwise.
func (o *RawGroupRepositoryApiRequest) GetRaw() RawAttributes {
	if o == nil || IsNil(o.Raw) {
		var ret RawAttributes
		return ret
	}
	return *o.Raw
}

// GetRawOk returns a tuple with the Raw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RawGroupRepositoryApiRequest) GetRawOk() (*RawAttributes, bool) {
	if o == nil || IsNil(o.Raw) {
		return nil, false
	}
	return o.Raw, true
}

// HasRaw returns a boolean if a field has been set.
func (o *RawGroupRepositoryApiRequest) HasRaw() bool {
	if o != nil && !IsNil(o.Raw) {
		return true
	}

	return false
}

// SetRaw gets a reference to the given RawAttributes and assigns it to the Raw field.
func (o *RawGroupRepositoryApiRequest) SetRaw(v RawAttributes) {
	o.Raw = &v
}

// GetStorage returns the Storage field value
func (o *RawGroupRepositoryApiRequest) GetStorage() StorageAttributes {
	if o == nil {
		var ret StorageAttributes
		return ret
	}

	return o.Storage
}

// GetStorageOk returns a tuple with the Storage field value
// and a boolean to check if the value has been set.
func (o *RawGroupRepositoryApiRequest) GetStorageOk() (*StorageAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Storage, true
}

// SetStorage sets field value
func (o *RawGroupRepositoryApiRequest) SetStorage(v StorageAttributes) {
	o.Storage = v
}

func (o RawGroupRepositoryApiRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RawGroupRepositoryApiRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["group"] = o.Group
	toSerialize["name"] = o.Name
	toSerialize["online"] = o.Online
	if !IsNil(o.Raw) {
		toSerialize["raw"] = o.Raw
	}
	toSerialize["storage"] = o.Storage
	return toSerialize, nil
}

func (o *RawGroupRepositoryApiRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"group",
		"name",
		"online",
		"storage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRawGroupRepositoryApiRequest := _RawGroupRepositoryApiRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRawGroupRepositoryApiRequest)

	if err != nil {
		return err
	}

	*o = RawGroupRepositoryApiRequest(varRawGroupRepositoryApiRequest)

	return err
}

type NullableRawGroupRepositoryApiRequest struct {
	value *RawGroupRepositoryApiRequest
	isSet bool
}

func (v NullableRawGroupRepositoryApiRequest) Get() *RawGroupRepositoryApiRequest {
	return v.value
}

func (v *NullableRawGroupRepositoryApiRequest) Set(val *RawGroupRepositoryApiRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRawGroupRepositoryApiRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRawGroupRepositoryApiRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRawGroupRepositoryApiRequest(val *RawGroupRepositoryApiRequest) *NullableRawGroupRepositoryApiRequest {
	return &NullableRawGroupRepositoryApiRequest{value: val, isSet: true}
}

func (v NullableRawGroupRepositoryApiRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRawGroupRepositoryApiRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


