/*
Sonatype Nexus Repository Manager

This documents the available APIs into [Sonatype Nexus Repository Manager](https://www.sonatype.com/products/sonatype-nexus-repository) as of version 3.93.2-01.

API version: 3.93.2-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EntryXO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntryXO{}

// EntryXO Request to add an IP Allow List entry
type EntryXO struct {
	// Optional description for this IP address
	Description *string `json:"description,omitempty"`
	// IP address or CIDR notation to add
	IpOrCidr string `json:"ipOrCidr"`
}

type _EntryXO EntryXO

// NewEntryXO instantiates a new EntryXO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntryXO(ipOrCidr string) *EntryXO {
	this := EntryXO{}
	this.IpOrCidr = ipOrCidr
	return &this
}

// NewEntryXOWithDefaults instantiates a new EntryXO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntryXOWithDefaults() *EntryXO {
	this := EntryXO{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EntryXO) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntryXO) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EntryXO) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EntryXO) SetDescription(v string) {
	o.Description = &v
}

// GetIpOrCidr returns the IpOrCidr field value
func (o *EntryXO) GetIpOrCidr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpOrCidr
}

// GetIpOrCidrOk returns a tuple with the IpOrCidr field value
// and a boolean to check if the value has been set.
func (o *EntryXO) GetIpOrCidrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpOrCidr, true
}

// SetIpOrCidr sets field value
func (o *EntryXO) SetIpOrCidr(v string) {
	o.IpOrCidr = v
}

func (o EntryXO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntryXO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["ipOrCidr"] = o.IpOrCidr
	return toSerialize, nil
}

func (o *EntryXO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ipOrCidr",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntryXO := _EntryXO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntryXO)

	if err != nil {
		return err
	}

	*o = EntryXO(varEntryXO)

	return err
}

type NullableEntryXO struct {
	value *EntryXO
	isSet bool
}

func (v NullableEntryXO) Get() *EntryXO {
	return v.value
}

func (v *NullableEntryXO) Set(val *EntryXO) {
	v.value = val
	v.isSet = true
}

func (v NullableEntryXO) IsSet() bool {
	return v.isSet
}

func (v *NullableEntryXO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntryXO(val *EntryXO) *NullableEntryXO {
	return &NullableEntryXO{value: val, isSet: true}
}

func (v NullableEntryXO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntryXO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


